name: Zip Files

on: [workflow_dispatch]

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1
        with:
          files: .
          dest: result.zip
      - uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: result.zip
